language: generic
sudo: required

services:
  - docker

env:
  - TRAVIS_DEBIAN_DISTRIBUTION=stretch
  - TRAVIS_DEBIAN_DISTRIBUTION=buster
  - TRAVIS_DEBIAN_DISTRIBUTION=unstable TRAVIS_DEBIAN_INCREMENT_VERSION_NUMBER=true

script:
  - ./travis/execute.sh

matrix:
  fast_finish: true
